# Use an official Node.js LTS version as the base image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the VueJS application
RUN npm run build

#Set Node environment
ENV NODE_ENV=development

# Expose the port on which the VueJS application will run
EXPOSE 7001

# Run the VueJS application in production mode
CMD ["npm", "run", "dev"]
